// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVcm2n_Nwcn0eDvPuQzfkSsaP7pICsOyw',
    appId: '1:59585418618:web:6774ba7a7a1f5d9411f2c3',
    messagingSenderId: '59585418618',
    projectId: 'prj-pabii-film',
    authDomain: 'prj-pabii-film.firebaseapp.com',
    storageBucket: 'prj-pabii-film.firebasestorage.app',
    measurementId: 'G-39MEHM2HJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC95ITFe4gkIrRDtbTAhyyUy1jz13Fqhc',
    appId: '1:59585418618:android:03898a5faac12c2011f2c3',
    messagingSenderId: '59585418618',
    projectId: 'prj-pabii-film',
    storageBucket: 'prj-pabii-film.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBozBjVXuD57iyKuKCEXkR0aUEFGxrkrcA',
    appId: '1:59585418618:ios:307dc29b97ac851d11f2c3',
    messagingSenderId: '59585418618',
    projectId: 'prj-pabii-film',
    storageBucket: 'prj-pabii-film.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFilm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBozBjVXuD57iyKuKCEXkR0aUEFGxrkrcA',
    appId: '1:59585418618:ios:307dc29b97ac851d11f2c3',
    messagingSenderId: '59585418618',
    projectId: 'prj-pabii-film',
    storageBucket: 'prj-pabii-film.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFilm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVcm2n_Nwcn0eDvPuQzfkSsaP7pICsOyw',
    appId: '1:59585418618:web:89fd8906b591fb2611f2c3',
    messagingSenderId: '59585418618',
    projectId: 'prj-pabii-film',
    authDomain: 'prj-pabii-film.firebaseapp.com',
    storageBucket: 'prj-pabii-film.firebasestorage.app',
    measurementId: 'G-3WHH4EGD5Q',
  );
}
